matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode7.3
    - os: linux
      language: android
      sudo: true
      android:
        components:
          - platform-tools
          - tools
          - build-tools-23.0.3
          - build-tools-23.0.1
          - android-23
          - extra-android-m2repository
          - extra-google-m2repository

before_install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.0/install.sh | bash
  - source ~/.bashrc
  - nvm install 5.6
  - npm install -g react-native-cli

before_script:
  - cd ..
  - react-native init TestBarcode && cd TestBarcode
  - npm install --save ../react-native-barcode-scanner-universal

script:
  - react-native link react-native-barcodescanner
  - react-native link react-native-camera
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xctool -project ios/TestBarcode.xcodeproj -scheme TestBarcode -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO DEAD_CODE_STRIPPING=NO; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd android; TERM=dumb ./gradlew assembleRelease; fi
